// app/api/orders/create/route.ts
import { NextResponse } from 'next/server';
import { getPool } from '@/lib/db';
import { notifyNewOrderPlaced } from '@/lib/portal-notifications';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    const {
      // Customer Info
      customerName,
      customerPhone,
      customerEmail,
      
      // Order Type
      orderType, // 'combo' or 'customize'
      comboId,
      
      // Address
      installationAddress,
      pincode,
      city,
      state,
      
      // Technical Details (for customize)
      cameraType,
      brand,
      channels,
      dvrModel,
      indoorCameras,
      outdoorCameras,
      storageSize,
      cableOption,
      includesAccessories,
      includesInstallation,
      
      // Pricing
      subtotal,
      installationCharges,
      deliveryCharges,
      taxAmount,
      discountAmount,
      totalAmount,
      
      // Delivery
      expectedDeliveryDate,
      expectedInstallationDate,
      
      // Payment
      paymentMethod,
      paymentStatus,
      status,
      
      // Bill of Materials
      billOfMaterials
    } = body;

    // Validation
    if (!customerName || !customerPhone || !installationAddress || !pincode || !totalAmount) {
      return NextResponse.json({
        success: false,
        message: 'Required fields missing: name, phone, address, pincode, total amount'
      }, { status: 400 });
    }

    const pool = getPool();

    // Start transaction
    await pool.query('BEGIN');

    try {
      // Insert order (order_number will be auto-generated by trigger)
      const orderResult = await pool.query(
        `INSERT INTO orders (
          customer_name, customer_phone, customer_email,
          order_type, combo_id,
          installation_address, pincode, city, state,
          camera_type, brand, channels, dvr_model,
          indoor_cameras, outdoor_cameras, storage_size, cable_option,
          includes_accessories, includes_installation,
          subtotal, installation_charges, delivery_charges, tax_amount, discount_amount, total_amount,
          expected_delivery_date, installation_date,
          payment_method, payment_status, status
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
          $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30
        ) RETURNING order_id, order_number`,
        [
          customerName, customerPhone, customerEmail || null,
          orderType, comboId || null,
          installationAddress, pincode, city || null, state || null,
          cameraType || null, brand || null, channels || null, dvrModel || null,
          indoorCameras ? JSON.stringify(indoorCameras) : null,
          outdoorCameras ? JSON.stringify(outdoorCameras) : null,
          storageSize || null, cableOption || null,
          includesAccessories || false, includesInstallation || false,
          subtotal || 0, installationCharges || 0, deliveryCharges || 0,
          taxAmount || 0, discountAmount || 0, totalAmount,
          expectedDeliveryDate || null, expectedInstallationDate || null,
          paymentMethod || null, paymentStatus || 'Pending', status || 'Pending'
        ]
      );

      const { order_id, order_number } = orderResult.rows[0];

      // Insert order items (Bill of Materials) - Commented out as order_items table doesn't exist yet
      // if (billOfMaterials && billOfMaterials.length > 0) {
      //   for (const item of billOfMaterials) {
      //     await pool.query(
      //       `INSERT INTO order_items (
      //         order_id, item_type, item_name, item_description, quantity, unit_price, total_price
      //       ) VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      //       [
      //         order_id,
      //         item.type || 'Product',
      //         item.name,
      //         item.description || null,
      //         item.quantity,
      //         item.unitPrice || 0,
      //         item.totalPrice || (item.quantity * item.unitPrice)
      //       ]
      //     );
      //   }
      // }

      // Create initial status history - Commented out as order_status_history table doesn't exist yet
      // await pool.query(
      //   `INSERT INTO order_status_history (order_id, status, remarks)
      //    VALUES ($1, $2, $3)`,
      //   [order_id, 'Pending', 'Order created from website quotation']
      // );

      // Commit transaction
      await pool.query('COMMIT');

      // 🚀 TRIGGER ORDER ALLOCATION TO NEAREST DEALER
      try {
        const allocationResponse = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/api/order-allocation`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ orderId: order_id })
        });

        const allocationData = await allocationResponse.json();
        
        if (allocationData.success) {
          if (allocationData.allocated) {
            console.log(`✅ Order #${order_number} allocated to dealer: ${allocationData.dealer_name}`);
          } else if (allocationData.escalated_to_admin) {
            console.log(`⚠️ Order #${order_number} escalated to admin - no dealer has stock`);
          }
        } else {
          console.error(`❌ Order allocation failed for #${order_number}:`, allocationData.error);
        }
      } catch (allocationError) {
        // Don't fail the order if allocation fails - log and continue
        console.error('Order allocation error:', allocationError);
      }

      try {
        const notifyResult = await pool.query(
          `SELECT o.order_id, o.order_number, o.city, o.pincode, d.district AS dealer_district
           FROM orders o
           LEFT JOIN dealers d ON d.dealer_id = o.assigned_dealer_id
           WHERE o.order_id = $1`,
          [order_id]
        );
        const notifyOrder = notifyResult.rows[0] || { order_number, city, pincode };
        await notifyNewOrderPlaced({
          orderId: order_id,
          orderNumber: notifyOrder.order_number || order_number,
          customerName,
          city: notifyOrder.city || city || null,
          pincode: notifyOrder.pincode || pincode || null,
          totalAmount,
          district: notifyOrder.dealer_district || null,
        });
      } catch (notifyError) {
        console.error('Failed to send new-order portal notifications:', notifyError);
      }

      return NextResponse.json({
        success: true,
        message: 'Order created successfully',
        order: {
          orderId: order_id,
          orderNumber: order_number,
          totalAmount,
          status: 'Pending'
        }
      });

    } catch (err) {
      // Rollback on error
      await pool.query('ROLLBACK');
      throw err;
    }

  } catch (err: any) {
    console.error('Order creation error:', err);
    return NextResponse.json({
      success: false,
      message: 'Failed to create order',
      error: process.env.NODE_ENV === 'development' ? err.message : undefined
    }, { status: 500 });
  }
}
