// app/api/orders/create/route.ts
import { NextResponse } from 'next/server';
import { getPool } from '@/lib/db';
import { sendOrderConfirmationEmail } from '@/lib/email';
import { notifyNewOrderPlaced } from '@/lib/portal-notifications';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    const {
      // Customer Info
      customerName,
      customerPhone,
      customerEmail,
      
      // Order Type
      orderType, // 'combo' or 'customize'
      comboId,
      
      // Address
      installationAddress,
      pincode,
      city,
      state,
      
      // Technical Details (for customize)
      cameraType,
      brand,
      channels,
      dvrModel,
      indoorCameras,
      outdoorCameras,
      storageSize,
      cableOption,
      includesAccessories,
      includesInstallation,
      
      // Pricing
      subtotal,
      installationCharges,
      deliveryCharges,
      taxAmount,
      discountAmount,
      totalAmount,
      
      // Delivery
      expectedDeliveryDate,
      expectedInstallationDate,
      
      // Payment
      paymentMethod,
      paymentStatus,
      status,
      
      // Bill of Materials
      billOfMaterials
    } = body;

    // Validation
    if (!customerName || !customerPhone || !installationAddress || !pincode || !totalAmount) {
      return NextResponse.json({
        success: false,
        message: 'Required fields missing: name, phone, address, pincode, total amount'
      }, { status: 400 });
    }

    const pool = getPool();
    const client = await pool.connect();
    let clientReleased = false;

    // Start transaction on a dedicated connection.
    await client.query('BEGIN');

    try {
      // Insert order (order_number will be auto-generated by trigger)
      const orderResult = await client.query(
        `INSERT INTO orders (
          customer_name, customer_phone, customer_email,
          order_type, combo_id,
          installation_address, pincode, city, state,
          camera_type, brand, channels, dvr_model,
          indoor_cameras, outdoor_cameras, storage_size, cable_option,
          includes_accessories, includes_installation,
          subtotal, installation_charges, delivery_charges, tax_amount, discount_amount, total_amount,
          expected_delivery_date, installation_date,
          payment_method, payment_status, status
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
          $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30
        ) RETURNING order_id, order_number, order_token`,
        [
          customerName, customerPhone, customerEmail || null,
          orderType, comboId || null,
          installationAddress, pincode, city || null, state || null,
          cameraType || null, brand || null, channels || null, dvrModel || null,
          indoorCameras ? JSON.stringify(indoorCameras) : null,
          outdoorCameras ? JSON.stringify(outdoorCameras) : null,
          storageSize || null, cableOption || null,
          includesAccessories || false, includesInstallation || false,
          subtotal || 0, installationCharges || 0, deliveryCharges || 0,
          taxAmount || 0, discountAmount || 0, totalAmount,
          expectedDeliveryDate || null, expectedInstallationDate || null,
          paymentMethod || null, paymentStatus || 'Pending', status || 'Pending'
        ]
      );

      const { order_id, order_number, order_token } = orderResult.rows[0];

      // Insert order items (Bill of Materials) - Commented out as order_items table doesn't exist yet
      // if (billOfMaterials && billOfMaterials.length > 0) {
      //   for (const item of billOfMaterials) {
      //     await pool.query(
      //       `INSERT INTO order_items (
      //         order_id, item_type, item_name, item_description, quantity, unit_price, total_price
      //       ) VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      //       [
      //         order_id,
      //         item.type || 'Product',
      //         item.name,
      //         item.description || null,
      //         item.quantity,
      //         item.unitPrice || 0,
      //         item.totalPrice || (item.quantity * item.unitPrice)
      //       ]
      //     );
      //   }
      // }

      // Create initial status history - Commented out as order_status_history table doesn't exist yet
      // await pool.query(
      //   `INSERT INTO order_status_history (order_id, status, remarks)
      //    VALUES ($1, $2, $3)`,
      //   [order_id, 'Pending', 'Order created from website quotation']
      // );

      // Commit transaction
      await client.query('COMMIT');
      client.release();
      clientReleased = true;

      // 🚀 TRIGGER ORDER ALLOCATION TO NEAREST DEALER
      try {
        const allocationResponse = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/api/order-allocation`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ orderId: order_id })
        });

        const allocationData = await allocationResponse.json();
        
        if (allocationData.success) {
          if (allocationData.allocated) {
            console.log(`✅ Order #${order_number} allocated to dealer: ${allocationData.dealer_name}`);
          } else if (allocationData.escalated_to_admin) {
            console.log(`⚠️ Order #${order_number} escalated to admin - no dealer has stock`);
          }
        } else {
          console.error(`❌ Order allocation failed for #${order_number}:`, allocationData.error);
        }
      } catch (allocationError) {
        // Don't fail the order if allocation fails - log and continue
        console.error('Order allocation error:', allocationError);
      }

      let responseOrderNumber = order_number;
      let responseOrderToken: string | null = null;

      try {
        const notifyResult = await pool.query(
          `SELECT o.order_id, o.order_number, o.order_token, o.city, o.pincode, d.district AS dealer_district
           FROM orders o
           LEFT JOIN dealers d ON d.dealer_id = o.assigned_dealer_id
           WHERE o.order_id = $1`,
          [order_id]
        );
        const notifyOrder = notifyResult.rows[0] || { order_number, city, pincode };
        responseOrderNumber = notifyOrder.order_number || order_number;
        responseOrderToken = notifyOrder.order_token || null;
        await notifyNewOrderPlaced({
          orderId: order_id,
          orderNumber: responseOrderNumber,
          customerName,
          city: notifyOrder.city || city || null,
          pincode: notifyOrder.pincode || pincode || null,
          totalAmount,
          district: notifyOrder.dealer_district || null,
        });
      } catch (notifyError) {
        console.error('Failed to send new-order portal notifications:', notifyError);
      }

      let emailSent = false;
      if (false && customerEmail) {
        try {
          const [fullOrderResult, orderItemsResult] = await Promise.all([
            pool.query(
              `SELECT o.*,
                d.business_name AS dealer_business_name,
                d.full_name AS dealer_full_name,
                d.unique_dealer_id AS dealer_unique_id,
                d.dealer_id AS dealer_id,
                d.phone_number AS dealer_phone,
                d.gstin AS dealer_gstin,
                d.business_address AS dealer_address,
                d.pincode AS dealer_pincode,
                d.location AS dealer_location,
                d.state AS dealer_state,
                d.district AS dealer_district
              FROM orders o
              LEFT JOIN dealers d ON d.dealer_id = o.assigned_dealer_id
              WHERE o.order_id = $1`,
              [order_id]
            ),
            pool.query(
              `SELECT oi.item_name, oi.quantity, oi.unit_price, oi.total_price, oi.item_type,
                      COALESCE(
                        to_jsonb(dp)->>'product_code',
                        CASE WHEN oi.product_id IS NOT NULL THEN 'PIC' || LPAD(oi.product_id::text, 3, '0') END,
                        'PIC' || LPAD(COALESCE(to_jsonb(oi)->>'item_id', to_jsonb(oi)->>'id', '0'), 3, '0')
                      ) AS product_code,
                      COALESCE(to_jsonb(oi)->>'hsn_code', to_jsonb(dp)->>'hsn_code') AS hsn_code
               FROM order_items oi
               LEFT JOIN dealer_products dp ON dp.id = oi.product_id
               WHERE oi.order_id = $1
               ORDER BY COALESCE((to_jsonb(oi)->>'item_id')::int, (to_jsonb(oi)->>'id')::int, 0)`,
              [order_id]
            ),
          ]);

          const fullOrderData = fullOrderResult.rows[0] || {
            order_id,
            order_number: responseOrderNumber,
            order_token: responseOrderToken,
            customer_name: customerName,
            customer_phone: customerPhone,
            customer_email: customerEmail,
            total_amount: totalAmount,
            payment_method: paymentMethod || null,
            payment_status: paymentStatus || 'Pending',
            created_at: new Date().toISOString(),
          };
          responseOrderNumber = fullOrderData.order_number || responseOrderNumber;
          responseOrderToken = fullOrderData.order_token || responseOrderToken;

          const trackingUrl = `${process.env.NEXT_PUBLIC_WEBSITE_URL || 'http://localhost:3000'}/guest-track-order?token=${responseOrderToken || ''}`;
          emailSent = await sendOrderConfirmationEmail({
            orderNumber: responseOrderNumber,
            orderToken: responseOrderToken || '',
            customerName,
            customerEmail,
            totalAmount,
            paymentMethod: paymentMethod || 'Pending',
            paymentStatus: paymentStatus || 'Pending',
            orderDate: fullOrderData.created_at || new Date().toISOString(),
            trackingUrl,
            orderItems: orderItemsResult.rows,
            fullOrderData,
          });

          await pool.query(
            `INSERT INTO email_logs (order_id, recipient_email, email_type, subject, email_status, sent_at)
             VALUES ($1, $2, $3, $4, $5, $6)`,
            [
              order_id,
              customerEmail,
              'order_confirmation',
              `Order Confirmation - ${responseOrderNumber}`,
              emailSent ? 'sent' : 'failed',
              emailSent ? new Date() : null,
            ]
          );

          if (emailSent) {
            await pool.query(
              'UPDATE orders SET tracking_link_sent = true WHERE order_id = $1',
              [order_id]
            );
          }
        } catch (emailError) {
          console.error('Order confirmation email error (non-blocking):', emailError);
        }
      }

      return NextResponse.json({
        success: true,
        message: 'Order created successfully',
        order: {
          orderId: order_id,
          orderNumber: responseOrderNumber,
          totalAmount,
          status: 'Pending',
          emailSent,
        }
      });

    } catch (err) {
      if (!clientReleased) {
        try {
          await client.query('ROLLBACK');
        } catch (rollbackError) {
          console.error('Order creation rollback failed:', rollbackError);
        }
        client.release();
      }
      throw err;
    }

  } catch (err: any) {
    console.error('Order creation error:', err);
    return NextResponse.json({
      success: false,
      message: 'Failed to create order',
      error: process.env.NODE_ENV === 'development' ? err.message : undefined
    }, { status: 500 });
  }
}
